### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by balasankarc** [kares/test-unit-context#4]
Hi,
May I know what is the correct way of running the tests given in test folder? I tried running
`bundle exec rake` (ofcourse, after running bundle install), but got the following error
```
/home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/lib/test/unit/patches.rb:2:in `require': cannot load such file -- test/unit/testsuitecreator (LoadError)
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/lib/test/unit/patches.rb:2:in `<top (required)>'
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/lib/test/unit/context.rb:2:in `require'
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/lib/test/unit/context.rb:2:in `<top (required)>'
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/test/test_helper.rb:8:in `require'
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/test/test_helper.rb:8:in `<top (required)>'
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/test/test/unit/context/hooks_test.rb:1:in `require'
	from /home/balasankarc/packaging/test-unit-context/ruby-test-unit-context-0.4.0/test/test/unit/context/hooks_test.rb:1:in `<top (required)>'
	from /home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `require'
	from /home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib" "/home/balasankarc/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/test/unit/context/hooks_test.rb" "test/test/unit/context/shared_test.rb" "test/test/unit/context/spec_test.rb" "test/test/unit/context_test.rb" "test/test/unit/patches_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```
The issue seems to be about loading the file test/unit/testsuitecreator .

**Comment by kares** [comment]
seems a bug related to TU 3.x ... [making compatibility "hard" - renaming files](https://github.com/test-unit/test-unit/tree/master/lib/test/unit)

**Comment by balasankarc** [comment]
Thanks. It would be extremely helpful if the gem is also updated with this fix.

PS : I am packaging this gem for Debian and tests being run succesfully run surely increases  the acceptability of a gem. So, a version with this fix would be a great help.

**Comment by kares** [comment]
@balasankarc a (gem 0.5.0) release happened right after the fix ...

**Comment by balasankarc** [comment]
Ah. My bad. Rubygems page was cached. Sorry for the trouble. Thanks for the gem.
