### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by balasankarc** [kares/test-unit-context#5]
Hi. I tried running `bundle exec rake` (after running `bundle install`) but two tests are failing

```
$ bundle exec rake
/usr/bin/ruby2.2 -I"lib:test" -I"/var/lib/gems/2.2.0/gems/rake-10.5.0/lib" "/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/test/unit/context/hooks_test.rb" "test/test/unit/context/shared_test.rb" "test/test/unit/context/spec_test.rb" "test/test/unit/context_test.rb" "test/test/unit/patches_test.rb" 
Loaded suite /var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
...................................F
======================================================================================================================================
Failure: test: runs setup method block a la Shoulda(Test::Unit::Context::TestHooks::ContextWithSetupTeardownMethods)
/home/balasankarc/packaging/test-unit-context/alioth/3/test-unit-context/test/test/unit/context/hooks_test.rb:194:in `block (2 levels) in <class:TestHooks>'
     191:       SAMPLE_TEST.class_eval { attr_reader :one, :two }
     192:       
     193:       it "runs setup method block a la Shoulda" do
  => 194:         assert_equal 1, @test.one
     195:       end
     196: 
     197:       it "runs setup method block and regular callbacks" do
<1> expected but was
<nil>
======================================================================================================================================
.F
======================================================================================================================================
Failure: test: runs teardown method block a la Shoulda(Test::Unit::Context::TestHooks::ContextWithSetupTeardownMethods)
/home/balasankarc/packaging/test-unit-context/alioth/3/test-unit-context/test/test/unit/context/hooks_test.rb:202:in `block (2 levels) in <class:TestHooks>'
     199:       end
     200: 
     201:       it "runs teardown method block a la Shoulda" do
  => 202:         assert_equal 10, @test.two
     203:       end
     204: 
     205:       it "runs teardown method block and regular callbacks" do
<10> expected but was
<nil>
======================================================================================================================================
.............................

Finished in 0.034854081 seconds.
--------------------------------------------------------------------------------------------------------------------------------------
67 tests, 92 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.0149% passed
--------------------------------------------------------------------------------------------------------------------------------------
1922.30 tests/s, 2639.58 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/var/lib/gems/2.2.0/gems/rake-10.5.0/lib" "/var/lib/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/test/unit/context/hooks_test.rb" "test/test/unit/context/shared_test.rb" "test/test/unit/context/spec_test.rb" "test/test/unit/context_test.rb" "test/test/unit/patches_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)

```

As I am maintaining the Debian package of this gem, can you help me how to fix this issue?

**Comment by kares** [comment]
thanks @balasankarc ... seems like its not compatible with Test-Unit 3.1 - works under 3.0 (mostly still using it only with 2.x but I will take a look and release a new version if its resolved).

**Comment by kares** [comment]
turns out those test were fluky and they broke against 3.1.6 ... the failing cases were reviewed to be more isolated and test what they [were intended to](https://github.com/kares/test-unit-context/commit/b75149715c9220fece680179b0d66ba93921ebb5) (this was likely a fast-and-dirty copy-paste test case from context gem). the travis-ci testing matrix is now green.

**Comment by balasankarc** [comment]
Thanks. Applying b75149715c9220fece680179b0d66ba93921ebb5  fixed my issue.
